### ISSUE TITLE
Reproduce Result Issues

### ISSUE THREAD

**Issue by Des-Moines-38** [giuliomattolin/TSMixer#2]
First thanks for your efforts!
While I'm reproducing the results,the model fits well on most datasets except ETTh1 and ETTh2.
Results on ETTh1 and ETTh2 is much lower than paper's result.
Any suggestions?
![92572dd8-a215-46bd-ae20-9d67eaabba5b](https://github.com/user-attachments/assets/a4bc276a-787d-469f-b8bd-e2311effab75)

**Comment by giuliomattolin** [comment]
Hi @Des-Moines-38,

I tested the model only on the 4 datasets in the README since the authors in the original repo included only the hyperparameters for those datasets. Moreover, I saw that the hyperparameters that the authors suggested to reproduce the results in the original repo are different from the ones presented in the paper. For example, regarding the traffic dataset with prediction length 96, in the original repo they suggest to use ff_dim=64, while in the paper they declared to use ff_dim=256.

What hyperparameters have you used for your experiments? I will suggest you to try to explore all the hyperparameter tuning space illustrated in Table 8 in the original paper.

**Comment by Des-Moines-38** [comment]
Thanks for your reply!
I used the hyperparameters for ETTm dataset to train on ETTh dataset,so I doubted if the hyperparameters causes the differences.I tried different hyperparameters for ETTh1_predlen_336 and ETTh1_predlen_336 today and finally got  better results. So I think the differences probably result from hyperparameters.
Thanks for your efforts again, quite elegant code.
